# Generated by Django 4.1.1 on 2022-09-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('hashed_password', models.CharField(max_length=64)),
                ('last_login', models.DateTimeField(verbose_name='last login')),
            ],
        ),
    ]
